import Link from "next/link";
import { Users, Dumbbell, CalendarDays, Clock3, Plus, ArrowUpRight, ArrowRight, ChevronRight, Sparkles, MessageCircle, ClipboardCheck, TrendingUp, AlertCircle, CheckCheck, Trash2, Target } from "lucide-react";
import StatCard from "./StatCard";
import Avatar from "./Avatar";
import { type CoachDashboardData, type ActivityDay, type DashboardEvent, clientStatus, expiresSoon, daysUntil, localDateLabel, dateKey } from "@/lib/dashboard";

export function ProgressRing({ percent, label = "COMPLETION" }: { percent: number | null; label?: string }) {
  const value = Math.max(0, Math.min(100, percent ?? 0));
  return <div className="hero-progress-ring" role="img" aria-label={percent === null ? "No scheduled workouts to measure" : `${percent}% ${label.toLowerCase()}`}><svg viewBox="0 0 120 120" aria-hidden="true"><circle className="ring-track" cx="60" cy="60" r="53"/><circle className="ring-value" cx="60" cy="60" r="53" strokeDasharray={`${value / 100 * 333} 333`}/></svg><div><strong>{percent === null ? "--" : `${percent}%`}</strong><span>{label}</span></div></div>;
}
export function ActivityChart({ days }: { days: ActivityDay[] }) {
  const max = Math.max(4, ...days.map(d => d.planned), ...days.map(d => d.completed));
  return <div className="activity-chart" role="img" aria-label={`Training activity: ${days.map(d => `${d.label} ${d.completed} completed of ${d.planned} scheduled`).join("; ")}`}><div className="chart-axis"><span>{max}</span><span>{Math.round(max * .75)}</span><span>{Math.round(max / 2)}</span><span>{Math.round(max * .25)}</span><span>0</span></div><div className="chart-bars">{days.map(d => <div key={d.date} className="chart-column" tabIndex={0} aria-label={`${localDateLabel(d.date)}: ${d.completed} completed, ${d.planned} scheduled`}><span className="chart-tooltip">{d.completed} / {d.planned} completed</span><div className="chart-bar-area"><div className="chart-bar planned" style={{ height: `${d.planned / max * 100}%`, opacity: d.planned ? 1 : .2 }}/><div className="chart-bar" style={{ height: `${d.completed / max * 100}%`, opacity: d.completed ? 1 : .2 }}/></div><span className="chart-column-label">{d.label}</span></div>)}</div></div>;
}
export function SessionList({ events, demo = false, staff = true, onDelete }: { events: DashboardEvent[]; demo?: boolean; staff?: boolean; onDelete?: (id: string) => void }) {
  if (!events.length) return <div className="empty-state"><CalendarDays size={24}/><h3>A little breathing room</h3><p>No sessions scheduled for this day.</p></div>;
  return <div>{events.map(event => <div className="session-row" key={event.id}><span className="session-time">{event.start_time?.slice(0, 5) || "Anytime"}</span><span className="session-divider" style={event.client_completed ? { background: "#8abfa2" } : undefined}/><Link className="session-details" href={demo ? "/preview" : !staff ? "/dashboard/schedule" : event.client_id ? `/dashboard/clients/${event.client_id}` : "/dashboard/sessions"}><strong>{event.title}</strong><small>{event.client?.full_name ? <><Users size={10}/>{event.client.full_name}</> : <><Clock3 size={10}/>{event.event_scope === "personal" ? "Your calendar" : "Your programme"}</>}{event.end_time && ` / until ${event.end_time.slice(0, 5)}`}</small></Link><span className={`session-status ${event.client_completed ? "done" : ""}`}>{event.client_completed ? "Completed" : event.event_type === "rest" ? "Recovery" : "Scheduled"}</span>{onDelete && <button className="icon-button" onClick={() => onDelete(event.id)} aria-label={`Delete ${event.title}`}><Trash2 size={13}/></button>}</div>)}</div>;
}
export default function CoachDashboardView({ name, data, demo = false, onDateChange, onAddEvent, onDeleteEvent }: { name: string; data: CoachDashboardData; demo?: boolean; onDateChange?: (date: string) => void; onAddEvent?: () => void; onDeleteEvent?: (id: string) => void }) {
  const to = (href: string) => demo ? "/preview" : href;
  const active = data.clients.filter(c => clientStatus(c) === "active").length;
  const renewing = data.clients.filter(c => expiresSoon(c.expiresAt));
  const unread = data.clients.filter(c => c.unread);
  const planned = data.activity.reduce((n, d) => n + d.planned, 0);
  const completed = data.activity.reduce((n, d) => n + d.completed, 0);
  const percentage = planned ? Math.round(completed / planned * 100) : null;
  return <>
    <div className="page-heading"><div><h1>Welcome back, {name.split(" ")[0] || "Coach"}.</h1><p>A clear view of your clients. A better day of coaching.</p></div><div className="page-heading-actions"><Link href={to("/dashboard/sessions")} className="btn-secondary"><CalendarDays size={14}/>View schedule</Link><Link href={to("/dashboard/admin")} className="btn-primary"><Plus size={15}/>Invite client</Link></div></div>
    <section className="hero-panel"><div className="hero-copy"><span className="eyebrow"><Sparkles size={11}/>THE MOVEMENT MINDSET</span><h2>A little progress.<br/><em>Every single day.</em></h2><p>Keep your clients moving forward. The plans, the check-ins, the small wins. All in one place.</p><Link className="hero-link" href={to("/dashboard/clients")}>Let's build some momentum <ArrowRight size={13}/></Link></div><div className="hero-summary"><ProgressRing percent={percentage}/><div className="hero-summary-copy"><span className="eyebrow">THE LAST 7 DAYS</span><h3>Your coaching in motion</h3><p>{planned ? `${completed} of ${planned} scheduled workouts marked complete by your clients.` : "Assign your first workouts and watch your clients build momentum."}</p><span className="badge badge-gold"><TrendingUp size={10}/>{planned ? "One session at a time" : "Ready for a fresh start"}</span></div></div></section>
    <div className="stats-grid"><StatCard label="Active clients" value={active} icon={Users} sub={`${data.clients.length} clients in your roster`} href={to("/dashboard/clients")}/><StatCard label="Training plans" value={data.planCount} icon={Dumbbell} sub="Built for better results" href={to("/dashboard/programs")}/><StatCard label="Upcoming sessions" value={data.upcomingCount} icon={CalendarDays} sub="Scheduled over the next 7 days" href={to("/dashboard/sessions")}/><StatCard label="Renewals due" value={renewing.length} icon={Clock3} sub="Account access ending in 7 days" href={to("/dashboard/clients")}/></div>
    <div className="dashboard-columns"><div className="dashboard-stack">
      <section className="card panel"><div className="panel-heading"><div><h2>Client training activity</h2><p>Small efforts. Real consistency.</p></div><span className="panel-tag"><CalendarDays size={11}/>Last 7 days</span></div><div className="chart-summary"><strong>{completed}</strong><span>workouts completed<br/>across your clients</span><div className="chart-legend"><span><i/>Completed</span><span><i/>Scheduled</span></div></div><ActivityChart days={data.activity}/><div className="panel-footnote"><CheckCheck size={12}/>Based on client-marked training sessions, including today.</div></section>
      <section className="card panel"><div className="panel-heading"><div><h2>{data.selectedDate === dateKey() ? "Today's schedule" : localDateLabel(data.selectedDate, "EEEE, d MMM")}</h2><p>Your sessions, classes and coaching calls.</p></div><div className="flex items-center gap-2">{onDateChange && <input type="date" aria-label="Choose schedule date" value={data.selectedDate} onChange={e => e.target.value && onDateChange(e.target.value)} className="schedule-date"/>}{onAddEvent ? <button className="icon-button" onClick={onAddEvent} aria-label="Add calendar event"><Plus size={17}/></button> : <Link href={to("/dashboard/sessions")} className="panel-action">View all<ArrowUpRight size={13}/></Link>}</div></div><SessionList events={data.dayEvents} demo={demo} onDelete={onDeleteEvent}/></section>
    </div><div className="dashboard-stack">
      <section className="card panel"><div className="panel-heading"><div><h2>Needs your attention</h2><p>A few things to keep moving.</p></div><span className="focus-pill">{unread.length + renewing.length}</span></div>{!unread.length && !renewing.length ? <div className="empty-state"><CheckCheck size={25}/><h3>You're all caught up</h3><p>No unread client messages or upcoming renewals.</p></div> : <div>{unread.slice(0, 3).map(c => <Link key={`msg-${c.id}`} href={to("/dashboard/messages")} className="attention-row"><Avatar name={c.name} url={c.avatarUrl} size={33}/><span><strong>{c.name}</strong><small>Unread message waiting for you</small></span><MessageCircle size={14}/></Link>)}{renewing.slice(0, Math.max(1, 4 - unread.slice(0, 3).length)).map(c => <Link key={`exp-${c.id}`} href={to(`/dashboard/clients/${c.id}`)} className="attention-row"><span className="attention-indicator"><Clock3 size={16}/></span><span><strong>{c.name}</strong><small>Access ends {daysUntil(c.expiresAt!) === 0 ? "today" : `in ${daysUntil(c.expiresAt!)} days`}</small></span><ChevronRight size={14}/></Link>)}</div>}<Link href={to("/dashboard/clients")} className="panel-action mt-4">Open your client roster<ArrowRight size={12}/></Link></section>
      <section className="card panel"><div className="panel-heading"><div><h2>Make your next move</h2><p>The things you do most, one click away.</p></div></div><div className="quick-links">{[{ href: "/dashboard/programs", label: "Training plans", icon: Dumbbell }, { href: "/dashboard/checkins", label: "Check-ins", icon: ClipboardCheck }, { href: "/dashboard/progress/pt", label: "Client progress", icon: TrendingUp }, { href: "/dashboard/messages", label: "Messages", icon: MessageCircle }].map(item => <Link key={item.href} className="quick-link" href={to(item.href)}><item.icon size={15}/>{item.label}<ArrowUpRight className="arrow" size={12}/></Link>)}</div></section>
      <section className="coaching-note"><span className="eyebrow"><Target size={12}/>COACH'S CORNER</span><h3>Great coaching starts<br/>with showing up.</h3><p>Check in. Celebrate the small wins.<br/>Help someone take their next step.</p><Link href={to("/dashboard/checkins")}>See how your clients are doing<ArrowUpRight size={12}/></Link></section>
    </div></div>
  </>;
}
